server:
  port: 8003

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: app-common
          uri: lb://micro-common
          predicates:
            - Path=/common/**, /static/**, /user/**
        - id: app-order
          uri: lb://micro-order
          predicates:
            - Path=/order/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@uriKeyResolver}'
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 3
  redis:
    port: 6379
    host: 127.0.0.1
    password:
    database: 0
eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 20
  client:
    service-url:
      defaultZone: http://127.0.0.1:9001/eureka
info:
  app.name: micro-MyGateway
  company.name: www.yuyongchang.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
